---

- name: deploy launchers
  vars:
    launchname: "{{ item.launchname }}"
    comment: "{{ item.comment }}"
    execut: "{{ item.exec }}"
    icon_path: "{{ item.icon_path | default(icon_path_default) }}"
    icon_name: "{{ item.icon_name | default(false) }}"
    term: "{{ item.term | default(launcher_term) }}"
    minetype: "{{ item.minetype | default(false) }}"
    type: "{{ item.type | default(launcher_type) }}"
    autostart: "{{ item.autostart | default(false) }}"
    categories: "{{ item.categories }}"
  template:
    src: "launchers.j2"
    dest: "/usr/share/applications/{{ item.launchname }}.desktop"
  with_items: 
    - "{{ launcher_vars }}"

- name: ensure icon folder exist
  file:
    path: "{{ item.icon_path | default(icon_path_default) }}"
    state: directory
  with_items:
    "{{ launcher_vars }}"
  when: item.icon_copy is not defined

- name: Copy icons
  copy:
    src: "{{ item.icon_name }}"
    dest: "{{ item.icon_path+item.icon_name if item.icon_path is defined else icon_path_default+item.icon_name }}"
  with_items:
    "{{ launcher_vars }}"
  when: item.icon_name is defined and item.icon_copy is not defined

...
